{{- /* This is a comment that isn't echoed to screen OR yaml sent to kubernetes */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wms.fullname" . }}
  labels:
    {{- /* Include the common labels */ -}}
{{- include "wms.labels" . | nindent 4 }}
    {{- /* Include any labels unique to this service */ -}}
    {{- /* It is not using indent because the indent of the function is used */ -}}
    {{- if .Values.deployment.labels }}
{{ tpl (toYaml .Values.deployment.labels) . | nindent 4 }}
    {{- end }}
  {{- if .Values.deployment.annotations }}
  annotations:
{{ tpl (toYaml .Values.deployment.annotations) . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- /* Include the common labels */ -}}
        {{- include "wms.labels" . | nindent 8 }}
        {{- /* Include any labels unique to this service */ -}}
        {{- if .Values.deployment.template.labels }}
{{ tpl (toYaml .Values.deployment.template.labels) . | nindent 8}}
        {{- end }}
      {{- if .Values.deployment.template.annotations }}
      annotations:
{{ tpl (toYaml .Values.deployment.template.annotations) . | nindent 8}}
      {{- end }}
    spec:
      serviceAccountName: {{ include "wms.serviceAccountName" . }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
{{- tpl (toYaml .Values.deployment.podSecurityContext) . | nindent 8}}
      {{- end }}
      initContainers:
      - image: "{{ .Values.appd.imageRepository }}:{{ .Values.appd.imageTag }}"
        imagePullPolicy: {{ .Values.appd.imagePullPolicy }}
        name: {{ .Chart.Name }}-init-appd
        command: ["cp", "-r", "/opt/appdynamics", "/appd/appdserveragent"]
        {{- if .Values.appd.volumeMounts }}
        volumeMounts:
{{ tpl (toYaml .Values.appd.volumeMounts) . | indent 12}}
        {{- end }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        {{- if .Values.appd.securityContext }}
        securityContext:
{{- tpl (toYaml .Values.appd.securityContext) . | nindent 12}}
        {{- end }}
        {{- with .Values.appd.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.appd.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.appd.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.appd.resources }}
        resources:
        {{- toYaml .Values.appd.resources | nindent 10 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.wms.imageRepository }}:{{ .Values.wms.imageTag }}"
          imagePullPolicy: {{ .Values.wms.imagePullPolicy }}
          {{- if .Values.wms.securityContext }}
          securityContext:
{{- tpl (toYaml .Values.wms.securityContext) . | nindent 12}}
          {{- end }}
      {{- if .Values.wms.volumeMounts }}
          volumeMounts:
{{ tpl (toYaml .Values.wms.volumeMounts) . | indent 12}}
      {{- end }}
          ports:
{{ tpl (toYaml .Values.wms.ports) . | indent 12}}
          env:
            - name: TARGET_DB_HOST
              value: {{ default "" .Values.sqlHost | quote }}
            - name: TARGET_DB_NAME
              value: {{ default "" .Values.sqlDbName | quote }}
            - name: TARGET_DB_USR
              value: {{ default "" .Values.sqlUser | quote }}
            - name: TARGET_DB_PSW
              value: {{ default "" .Values.sqlPassword | quote }}
            - name: TARGET_REFS_HOST
              value: {{ default "" .Values.refsHost | quote }}
            - name: TARGET_REFS_HOST_PORT
              value: {{ default "" .Values.refsPort | quote }}
            - name: CONFIG_PSR
              value: {{ int .Values.psr.enabled | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MOCA_JAVA_VMARGS
              value: {{ default "" .Values.wms.envJavaVMargs | quote }}
          {{- if .Values.wms.startupProbe }}
          startupProbe:
{{ tpl (toYaml .Values.wms.startupProbe) . | indent 12}}
          {{- end }}
          {{- if .Values.wms.readinessProbe }}
          readinessProbe:
{{ tpl (toYaml .Values.wms.readinessProbe) . | indent 12}}
          {{- end }}
          {{- if .Values.wms.livenessProbe }}
          livenessProbe:
{{ tpl (toYaml .Values.wms.livenessProbe) . | indent 12}}
          {{- end }}
          {{- with .Values.wms.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.wms.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.wms.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.wms.resources }}
          resources:
            {{- toYaml .Values.wms.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
{{ tpl (toYaml .Values.deployment.volumes) . | indent 8}}
      {{- end }}


