{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wms.serviceAccountName" . }}
  labels:
    {{- /* Include the common labels */ -}}
    {{- include "wms.labels" . | nindent 4 }}
    {{- /* Include any labels unique to this service */ -}}
    {{- /* It is not using indent because the indent of the function is used */ -}}
    {{- if .labels }}
    {{ tpl (toYaml .Values.serviceAccount.labels) . }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
