{{- /* This is a comment that isn't echoed to screen OR yaml sent to kubernetes*/ -}}
{{- /* We are going to loop and create as many services as we need */ -}}
{{- range .Values.ingress }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .name }}
  name: {{ .name }}
  {{- else }}
  name: {{ template "wms.fullname" $ }}
  {{- end }}
  labels:
    {{- /* Include the common labels */ -}}
    {{- include "wms.labels" $ | nindent 4 }}
    {{- /* Include any labels unique to this service */ -}}
    {{- /* It is not using indent because the indent of the function is used */ -}}
    {{- if .labels }}
    {{ tpl (toYaml .labels) $ }}
    {{- end }}
  {{- if .annotations }}
  annotations:
{{ tpl (toYaml .annotations) $ | indent 4 }}
  {{- end }}
spec:
  rules:
{{ tpl (toYaml .rules) $ | indent 2 }}
{{- end }}
