{{- /* This is a comment that isn't echoed to screen OR yaml sent to kubernetes*/ -}}
{{- /* We are going to loop and create as many pvc as we need */ -}}
{{- range .Values.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    {{- /* Include the common labels */ -}}
    {{- include "wms.labels" $ | nindent 4 }}
    {{- /* Include any labels unique to this service */ -}}
    {{- /* It is not using indent because the indent of the function is used */ -}}
    {{- if .labels }}
    {{ tpl (toYaml .labels) $ }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{ tpl (toYaml .annotations) $ }}
  {{- end }}
spec:
  accessModes:
    {{ toYaml .accessModes }}
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .requestsStorage }}
{{- end }}